[package]
name = "rustWasm"
version = "0.1.0"
authors = ["Prasad Zore"]
description = "Prime No. Code with wasm-pack"
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

